### ISSUE TITLE
Another Failure

### ISSUE THREAD

**Issue by johnrs** [xlab/handysort#3]
Sorry, but I think that I've found another failure case:
    []string{"1ax2", "1a10", "1ax", "1b", "1ax"}  ==>  [1ax2 1a10 1ax 1b 1ax]

And:
    []string{"1b", "1ax"}  ==>  [1b 1ax]

**Comment by xlab** [comment]
Seems that I've completely forgot about cases when there's a digit field in one string and a rune in another. Added lookahead for this, now it would advance and check runes after digit fields if these fields seem equal. I hope that'll cover all cases now.
